---
- name: Test MikroTik connectivity
  hosts: routers
  gather_facts: no

  tasks:
    - name: Show router identity
      community.routeros.command:
        commands:
          - /system identity print
      register: identity

    - name: Display output
      debug:
        var: identity.stdout_lines
