---
- name: Show MikroTik interfaces
  hosts: routers
  gather_facts: no

  tasks:
    - name: List interfaces
      community.routeros.command:
        commands:
          - /interface print
      register: interfaces

    - name: Display interfaces
      debug:
        var: interfaces.stdout_lines
